name: Build

on:
    workflow_dispatch:
        inputs:
            ref:
                description: "Branch or tag ref"
                required: false
                default: "main"

env:
    JAVA_VERSION: "21"

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.ref }}

            - name: Set up JDK ${{ env.JAVA_VERSION }}
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: ${{ env.JAVA_VERSION }}
                  cache: "maven"

            - name: Build and Test
              run: mvn clean verify --no-transfer-progress
