name: Manual Build

on:
    workflow_dispatch:
        inputs:
            ref:
                description: "Branch or tag ref"

env:
    JAVA_VERSION: "23"

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.inputs.ref }}
            - name: Set up JDK ${{ env.JAVA_VERSION }}
              uses: actions/setup-java@v3
              with:
                  distribution: adopt
                  java-version: ${{ env.JAVA_VERSION }}
            - name: Cache SonarQube packages
              uses: actions/cache@v4
              with:
                  path: ~/.sonar/cache
                  key: ${{ runner.os }}-sonar
                  restore-keys: ${{ runner.os }}-sonar
            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2
            - name: Build and analyze
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
              run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Postrise -Dsonar.projectName='Postrise'
            - name: maven-settings-xml-action
              uses: whelk-io/maven-settings-xml-action@v21
            - name: Maven Package
              run: mvn -B package --file pom.xml
              continue-on-error: false
